sudo: true
dist: xenial
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
#  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy"
  - "pypy3"
install: pip install tox-travis
script: tox
